// Code generated by MockGen. DO NOT EDIT.
// Source: datastore.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/datastore.go -source datastore.go
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	storage "github.com/stackrox/rox/generated/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockDataStore is a mock of DataStore interface.
type MockDataStore struct {
	ctrl     *gomock.Controller
	recorder *MockDataStoreMockRecorder
}

// MockDataStoreMockRecorder is the mock recorder for MockDataStore.
type MockDataStoreMockRecorder struct {
	mock *MockDataStore
}

// NewMockDataStore creates a new mock instance.
func NewMockDataStore(ctrl *gomock.Controller) *MockDataStore {
	mock := &MockDataStore{ctrl: ctrl}
	mock.recorder = &MockDataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataStore) EXPECT() *MockDataStoreMockRecorder {
	return m.recorder
}

// DeleteScanObject mocks base method.
func (m *MockDataStore) DeleteScanObject(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScanObject", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScanObject indicates an expected call of DeleteScanObject.
func (mr *MockDataStoreMockRecorder) DeleteScanObject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScanObject", reflect.TypeOf((*MockDataStore)(nil).DeleteScanObject), ctx, id)
}

// GetScanObject mocks base method.
func (m *MockDataStore) GetScanObject(ctx context.Context, id string) (*storage.ComplianceOperatorScanV2, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScanObject", ctx, id)
	ret0, _ := ret[0].(*storage.ComplianceOperatorScanV2)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetScanObject indicates an expected call of GetScanObject.
func (mr *MockDataStoreMockRecorder) GetScanObject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScanObject", reflect.TypeOf((*MockDataStore)(nil).GetScanObject), ctx, id)
}

// UpsertScanObject mocks base method.
func (m *MockDataStore) UpsertScanObject(ctx context.Context, result *storage.ComplianceOperatorScanV2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertScanObject", ctx, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertScanObject indicates an expected call of UpsertScanObject.
func (mr *MockDataStoreMockRecorder) UpsertScanObject(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertScanObject", reflect.TypeOf((*MockDataStore)(nil).UpsertScanObject), ctx, result)
}
