{{- include "srox.init" . -}}

{{- if not ._rox.scanner.disable }}
# TODO: What about openshift 3? Can we add the scanner ServiceAccount to the SCC via Helm?

{{- if eq ._rox.env.openshift 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-nonroot-v2-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "role" "use-nonroot-v2-scc") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "role" "use-nonroot-v2-scc") | nindent 4 }}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - nonroot-v2
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scanner-use-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "rolebinding" "scanner-use-scc") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "rolebinding" "scanner-use-scc") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-nonroot-v2-scc
subjects:
- kind: ServiceAccount
  name: scanner
  namespace: {{ .Release.Namespace }}
{{- end }}

{{- end }}
